-- DropForeignKey
ALTER TABLE `PidioExtra` DROP FOREIGN KEY `idE`;

-- AddForeignKey
ALTER TABLE `PidioExtra` ADD CONSTRAINT `idE` FOREIGN KEY (`idE`) REFERENCES `Extra`(`idE`) ON DELETE NO ACTION ON UPDATE NO ACTION;
